[[customizations.user]]
name = "rory"
password = "changeme"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD5o5yQjb2OeqEfJHWzjkyH88DYTgo5S0Fu4z8YXpJZk1Wnw56xjV2vwoKMEr9RiK93RYg5VcJ6zZuxtmHE6hA51ci26brZI1N0TvuQ8UhdBzapAth5vCfcnq+VXDRnWPWcsYTyhGrnbg04aCmGF5XOPaKaIkuo4MFB6fhq49avvxEJGyPRbxMGCBTj0amhY34hOFQsAhc0h03rt1W0exQNQX2QHh5v+pTgVb6pfL6iu+vN7SWzqI4Bxyc+wpROOcq57Wz7GVjCSIlqjBlbo55R6bCXBb87OovP2U8Hiih3EpE6eCQBjelRbnj9Q2goC2bUh2E7dGjUZEVpSNYnYjxtkYOhIeSWQoJedzNdWtYqvqv24hAlQU0n3U8J7u/iEu8AsQ9MIZks15HTz23Ux7+I0q+owvcDBC675E+iFR2uiNXC7ruEOdMUWe/1jHIM5v7RedQp123Q7YRBiknvrY2qv76f4eOdVNOdadtInYJR4YrhMKtgbwkFhJpUjUI8isVTvaPaKVBFVjUwLByG3iDI4umMRuc4XkBQWW+0XylfnZ79p5pogVMJGmqb1oT/HcWugph0Vck/IVWKxR88w7rJ5IrLwD0b0UNlYkK7ZSqkDA+tdImM/KU618n4jS076hnUextNQOFXf+Mtmq//WkRaPXgBQYnz7IhV7NesLdrHYQ== rory.schellekens@brightcubes.nl"
groups = ["wheel"]

#[customizations.installer.kickstart]
#contents = """
#text --non-interactive
#zerombr
#clearpart --all --initlabel --disklabel=gpt
#autopart --noswap --type=lvm
#network --bootproto=dhcp --device=link --activate --onboot=on
#"""
