# option details here: https://gitea.com/gitea/act_runner/src/branch/main/internal/pkg/config/config.example.yaml
runner:
  labels:
    - runner:docker://quay.io/mrguitar/gitea-buildah:latest
  capacity: 2

container:
  force_pull: true
  privileged: true
  options: --security-opt label=disable --security-opt seccomp=unconfined --device /dev/fuse:rw
  network: podman
